// <auto-generated />
namespace x_nova_template.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initialcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201601052024150_initialcreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
